version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev

  # Production service
  health-care-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: ghcr.io/ananddigimabble/healthcare-backend:latest
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - prod 